"""baseline schema: sessions, user_skills, resources, resource_skills + pgvector

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-21

Handwritten baseline (not autogenerated): it creates the pgvector extension and
the HNSW index, which autogenerate does not handle. From here on, schema changes
go through `alembic revision --autogenerate`.
"""
from __future__ import annotations

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

from app.core.config import settings

# revision identifiers, used by Alembic.
revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector must exist before any Vector column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "role_id", sa.String(), nullable=False, server_default="ai_engineer_applied"
        ),
        sa.Column("orientation", sa.String(), nullable=False, server_default="base"),
        sa.Column("status", sa.String(), nullable=False, server_default="in_progress"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "user_skills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("skill_id", sa.String(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "evidence_type", sa.String(), nullable=False, server_default="self_claim"
        ),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "skill_id", name="uq_session_skill"),
        sa.CheckConstraint("level >= 0 AND level <= 4", name="ck_user_skill_level"),
    )
    op.create_index("ix_user_skills_session_id", "user_skills", ["session_id"])
    op.create_index("ix_user_skills_skill_id", "user_skills", ["skill_id"])

    op.create_table(
        "resources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("url_hash", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False, server_default=""),
        sa.Column(
            "resource_type", sa.String(), nullable=False, server_default="article"
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.Vector(dim=settings.embedding_dim),
            nullable=True,
        ),
        sa.Column("quality_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "freshness_status", sa.String(), nullable=False, server_default="unverified"
        ),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("verify_note", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url", name="uq_resources_url"),
        sa.UniqueConstraint("url_hash", name="uq_resources_url_hash"),
        sa.CheckConstraint(
            "freshness_status IN ('unverified', 'fresh', 'stale', 'dead')",
            name="ck_resource_freshness_status",
        ),
    )
    op.create_index("ix_resources_url_hash", "resources", ["url_hash"])
    # HNSW approximate nearest-neighbour index for cosine similarity (pgvector).
    op.create_index(
        "ix_resources_embedding_hnsw",
        "resources",
        ["embedding"],
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )

    op.create_table(
        "resource_skills",
        sa.Column("resource_id", sa.String(), nullable=False),
        sa.Column("skill_id", sa.String(), nullable=False),
        sa.Column("target_level", sa.Integer(), nullable=False, server_default="1"),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["resources.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("resource_id", "skill_id"),
        sa.CheckConstraint(
            "target_level >= 0 AND target_level <= 4", name="ck_resource_skill_level"
        ),
    )
    op.create_index("ix_resource_skills_skill_id", "resource_skills", ["skill_id"])


def downgrade() -> None:
    op.drop_index("ix_resource_skills_skill_id", table_name="resource_skills")
    op.drop_table("resource_skills")
    op.drop_index("ix_resources_embedding_hnsw", table_name="resources")
    op.drop_index("ix_resources_url_hash", table_name="resources")
    op.drop_table("resources")
    op.drop_index("ix_user_skills_skill_id", table_name="user_skills")
    op.drop_index("ix_user_skills_session_id", table_name="user_skills")
    op.drop_table("user_skills")
    op.drop_table("sessions")
    # The `vector` extension is left installed on purpose (may be shared).
