"""add jd_documents and jd_evidence tables

Revision ID: 6c409e8fe1f3
Revises: 0001_baseline
Create Date: 2026-06-22 22:04:54.493083
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c409e8fe1f3'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jd_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('search_keyword', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('recruit_type', sa.String(), nullable=False),
    sa.Column('role_category', sa.String(), nullable=False),
    sa.Column('collected_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_jd_source_external')
    )
    op.create_index('ix_jd_documents_company', 'jd_documents', ['company'], unique=False)
    op.create_index('ix_jd_documents_source_id', 'jd_documents', ['source_id'], unique=False)
    op.create_table('jd_evidence',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('doc_count', sa.Integer(), nullable=False),
    sa.Column('doc_total', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('signal', sa.String(), nullable=False),
    sa.Column('in_graph', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('source_id', 'skill_id')
    )
    op.create_index('ix_jd_evidence_skill_id', 'jd_evidence', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jd_evidence_skill_id', table_name='jd_evidence')
    op.drop_table('jd_evidence')
    op.drop_index('ix_jd_documents_source_id', table_name='jd_documents')
    op.drop_index('ix_jd_documents_company', table_name='jd_documents')
    op.drop_table('jd_documents')
    # ### end Alembic commands ###
