"""add current_role to sessions

Revision ID: 995070c43545
Revises: 6c409e8fe1f3
Create Date: 2026-06-23 17:05:41.915766
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995070c43545'
down_revision = '6c409e8fe1f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_resources_url_hash'), 'resources', type_='unique')
    op.drop_index(op.f('ix_resources_url_hash'), table_name='resources')
    op.create_index(op.f('ix_resources_url_hash'), 'resources', ['url_hash'], unique=True)
    op.add_column('sessions', sa.Column('current_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'current_role')
    op.drop_index(op.f('ix_resources_url_hash'), table_name='resources')
    op.create_index(op.f('ix_resources_url_hash'), 'resources', ['url_hash'], unique=False)
    op.create_unique_constraint(op.f('uq_resources_url_hash'), 'resources', ['url_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
